-- MySQL Script generated by MySQL Workbench
-- 08/18/16 16:10:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cfrane1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cfrane1` DEFAULT CHARACTER SET utf8 ;
USE `cfrane1` ;

-- -----------------------------------------------------
-- Table `cfrane1`.`review_status`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cfrane1`.`review_status` (
  `review_status_id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`review_status_id`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC),
  UNIQUE INDEX `review_status_id_UNIQUE` (`review_status_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfrane1`.`organism`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cfrane1`.`organism` (
  `organism_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`organism_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `organism_id_UNIQUE` (`organism_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfrane1`.`review_info`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cfrane1`.`review_info` (
  `review_info_id` INT NOT NULL AUTO_INCREMENT,
  `info` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`review_info_id`),
  UNIQUE INDEX `review_info_id_UNIQUE` (`review_info_id` ASC),
  UNIQUE INDEX `info_UNIQUE` (`info` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfrane1`.`recog_seq`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cfrane1`.`recog_seq` (
  `recog_seq_id` INT NOT NULL AUTO_INCREMENT,
  `sequence` VARCHAR(45) NULL DEFAULT NULL,
  `primary_cut` VARCHAR(10) NULL DEFAULT NULL,
  `comp_cut` INT NULL DEFAULT NULL,
  PRIMARY KEY (`recog_seq_id`),
  UNIQUE INDEX `recog_seq_id_UNIQUE` (`recog_seq_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfrane1`.`enzyme`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cfrane1`.`enzyme` (
  `accession_num` VARCHAR(15) NOT NULL,
  `gene_name` VARCHAR(45) NULL DEFAULT NULL,
  `entry_name` VARCHAR(45) NULL DEFAULT NULL,
  `organism_id` INT NULL DEFAULT NULL,
  `review_info_id` INT NULL DEFAULT NULL,
  `review_status_id` INT NULL DEFAULT NULL,
  `recog_seq_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`accession_num`),
  UNIQUE INDEX `enzyme_id_UNIQUE` (`accession_num` ASC),
  UNIQUE INDEX `entry_name_UNIQUE` (`entry_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfrane1`.`protein_info`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cfrane1`.`protein_info` (
  `accession_num` VARCHAR(15) NOT NULL,
  `sequence` TEXT NULL DEFAULT NULL,
  `protein_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`accession_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfrane1`.`ec_info`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cfrane1`.`ec_info` (
  `ec_num` VARCHAR(15) NOT NULL,
  `info` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ec_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfrane1`.`ec_num`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cfrane1`.`ec_num` (
  `accession_num` VARCHAR(15) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`accession_num`, `number`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cfrane1`.`ec_info`
-- -----------------------------------------------------
START TRANSACTION;
USE `cfrane1`;
INSERT INTO `cfrane1`.`ec_info` (`ec_num`, `info`) VALUES ('3.1.21.3', 'Type-1 Restriction Enzyme');
INSERT INTO `cfrane1`.`ec_info` (`ec_num`, `info`) VALUES ('3.1.21.4', 'Type-2 Restriction Enzyme');
INSERT INTO `cfrane1`.`ec_info` (`ec_num`, `info`) VALUES ('3.1.21.5', 'Type-3 Restriction Enzyme');

COMMIT;


